name: Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - test  # Change this to your specific branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies and build the project
      - run: npm ci && npm run build

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FINALYEARPROJECT_E2C5A }}'
          channelId: live
          projectId: finalyearproject-e2c5a
          firebaseToolsVersion: '11'  # Specify the compatible Firebase version
